version: '3'

services:
  server:
    build: part_6
  web:
    image: nginx
    ports:
      - "80:8080"
    volumes:
      - ./part_6/proxy/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server
